[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "app"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025052905,<26"
pre-commit = ">=4.2.0,<5"
